name: Build MpcAsfTool.exe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-gcc
            base-devel
            mingw-w64-x86_64-wxwidgets3.2-msw

      - name: Compile resources
        run: |
          windres resource.rc -O coff -o resource.o

      - name: Build MpcAsfTool
        run: |
          g++ `wx-config --cxxflags` -o MpcAsfTool.exe *.cpp resource.o `wx-config --libs`

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: MpcAsfToolExe
          path: MpcAsfTool.exe
